DEBUG    urllib3.connectionpool:connectionpool.py:959 Starting new HTTPS connection (1): txqa.ziyun-cloud.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:437 https://txqa.ziyun-cloud.com:443 "GET /dnc/file/list/history?fileId=172&type=0 HTTP/1.1" 200 46
INFO     root:Log.py:65 [INFO 2020-09-18 15:19:12]----请求用时: 450.817 秒数
INFO     root:Log.py:65 [INFO 2020-09-18 15:19:12]---------------请求-----------------
https://txqa.ziyun-cloud.com/dnc/file/list/history?fileId=172&type=0
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
token: 6JUc7IoTNqh2f2SztWdPD0Lqziur3vLk0pB3jFuti7RBKZXgeNu2lipoNHht40wBNLcS_NygdjkwWoZoFRRt07E3rgww9QXsNJL_3-NVSsiebJNBrmVQLBl5FzY1Mf0ZEoWAsJbQb1R3To5qbEU6qjaBRB482UkdEIdnBBYfP6CirdciaRjuKPwCQP3-HyvJBzetH7WJsL2xkzSeL-KT2g08O2loQ6y2MKOrmDUumlxNk7v6AsWH3GL9ytozMJxK4wVgFjqwQvxhiiUShAx9TyzJlKtFXTLCvg18D11SfffPCJ0F4KKwzPyHmtxumNPOpTgdhBfb_PXUs-jwObiNbK1qianSvDu7bp41ztSyr9U=

None
INFO     root:Log.py:65 [INFO 2020-09-18 15:19:12]---------------响应----------------
200
Server: nginx/1.16.1
Date: Fri, 18 Sep 2020 07:19:11 GMT
Content-Type: application/json
Content-Length: 46
Connection: keep-alive
X-Frame-Options: ALLOWALL
Access-Control-Allow-Origin: *

{"code":500,"message":"Internal server error"}